root_list = [['root', 'test1', 'test4', '文本(9).txt'], ['root', 'test1', 'test4', '文本(2).txt'],
             ['root', 'test1', 'test4', '文本(4).txt'],
             ['root', 'test1', 'test4', '文本(5).txt'], ['root', 'test1', 'test4', '文本(6).txt'],
             ['root', 'test1', 'test4', '文本(7).txt'], ['root', 'test1', 'test4', '文本(8).txt'],
             ['root', 'test1', 'test4', '文本(1).txt'], ['root', 'test1', 'test4', '文本(13).txt'],
             ['root', 'test1', 'test4', '文本(11).txt'], ['root', 'test1', 'test4', '文本(12).txt'],
             ['root', 'test1', 'test4', '文本(10).txt'], ['root', 'test1', 'test4', '文本(14).txt'],
             ['root', 'test1', 'test4', '文本(15).txt'], ['root', 'test1', 'test4', '文本(17).txt'],
             ['root', 'test1', 'test4', '文本(16).txt'], ['root', 'test1', 'test2', '文本(1).txt'],
             ['root', 'test1', 'test2', '文本(9).txt'], ['root', 'test1', 'test2', '文本(2).txt'],
             ['root', 'test1', 'test2', '文本(3).txt'], ['root', 'test1', 'test2', '文本(4).txt'],
             ['root', 'test1', 'test2', '文本(5).txt'], ['root', 'test1', 'test2', '文本(6).txt'],
             ['root', 'test1', 'test2', '文本(7).txt'], ['root', 'test1', 'test2', '文本(8).txt'],
             ['root', 'test1', 'test2', '文本(1).txt'], ['root', 'test1', 'test2', '文本(13).txt'],
             ['root', 'test1', 'test2', '文本(11).txt'], ['root', 'test1', 'test2', '文本(12).txt'],
             ['root', 'test1', 'test2', '文本(10).txt'], ['root', 'test1', 'test2', '文本(14).txt'],
             ['root', 'test1', 'test2', '文本(15).txt'], ['root', 'test1', 'test2', '文本(17).txt'],
             ['root', 'test2', '文本(7).txt'], ['root', 'test2', '文本(6).txt'],
             ['root', 'test2', '文本(7).txt'], ['root', 'test2', '文本(5).txt'],
             ['root', 'test2', '文本(4).txt'], ['root', 'test2', '文本(3).txt'],
             ['root', 'test1', 'test4', '文本(3).txt'],
             ['root', 'test2', '文本(2).txt'], ['root', 'test2', '文本(1).txt'],
             ['root', 'test3', 'test1', '文本(7).txt'],
             ['root', 'test5', '文本(7).txt'],
             ['root', 'test5', '文本(7).jpg'],
             ['root', 'test5', '文本(7).png'],
             ['root', 'test5', '文本(7).jpeg'],
             ['root', 'test5', '文本(7).iso'],
             ['root', 'test5', '文本(7).dll'],
             ['root', 'test5', '文本(7).pkg'],
             ['root', 'test5', '文本(7).doc'],
             ['root', 'test5', '文本(7).ppt'],
             ['root', 'test5', '文本(7).xls'],
             ['root', 'test5', '文本(7).mp3']]
