# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileM.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileM(object):
    def setupUi(self, FileM):
        FileM.setObjectName("FileM")
        FileM.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(FileM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.lb_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_info.sizePolicy().hasHeightForWidth())
        self.lb_info.setSizePolicy(sizePolicy)
        self.lb_info.setText("")
        self.lb_info.setObjectName("lb_info")
        self.gridLayout.addWidget(self.lb_info, 3, 0, 1, 1)
        self.lb_sidebar = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_sidebar.sizePolicy().hasHeightForWidth())
        self.lb_sidebar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_sidebar.setFont(font)
        self.lb_sidebar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lb_sidebar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lb_sidebar.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lb_sidebar.setObjectName("lb_sidebar")
        self.gridLayout.addWidget(self.lb_sidebar, 1, 1, 1, 1)
        self.le_path = QtWidgets.QLineEdit(self.centralwidget)
        self.le_path.setObjectName("le_path")
        self.gridLayout.addWidget(self.le_path, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(150, 150))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.tv_catalogue = QtWidgets.QTreeView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tv_catalogue.sizePolicy().hasHeightForWidth())
        self.tv_catalogue.setSizePolicy(sizePolicy)
        self.tv_catalogue.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tv_catalogue.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tv_catalogue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tv_catalogue.setAlternatingRowColors(True)
        self.tv_catalogue.setObjectName("tv_catalogue")
        self.tv_catalogue.header().setVisible(True)
        self.tv_catalogue.header().setHighlightSections(True)
        self.lv_file = QtWidgets.QListView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_file.sizePolicy().hasHeightForWidth())
        self.lv_file.setSizePolicy(sizePolicy)
        self.lv_file.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lv_file.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_file.setObjectName("lv_file")
        self.lv_label = QtWidgets.QListView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_label.sizePolicy().hasHeightForWidth())
        self.lv_label.setSizePolicy(sizePolicy)
        self.lv_label.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lv_label.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_label.setObjectName("lv_label")
        self.gridLayout.addWidget(self.splitter, 2, 0, 1, 2)
        FileM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FileM)
        self.statusbar.setObjectName("statusbar")
        FileM.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(FileM)
        self.toolBar.setObjectName("toolBar")
        FileM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(FileM)
        QtCore.QMetaObject.connectSlotsByName(FileM)

    def retranslateUi(self, FileM):
        _translate = QtCore.QCoreApplication.translate
        FileM.setWindowTitle(_translate("FileM", "FileM"))
        self.lb_sidebar.setText(_translate("FileM", "文件标签栏"))
        self.le_path.setText(_translate("FileM", "/tmp"))
        self.toolBar.setWindowTitle(_translate("FileM", "toolBar"))

