# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileM.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileM(object):
    def setupUi(self, FileM):
        FileM.setObjectName("FileM")
        FileM.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(FileM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.le_path = QtWidgets.QLineEdit(self.centralwidget)
        self.le_path.setObjectName("le_path")
        self.verticalLayout_2.addWidget(self.le_path)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.lb_info = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_info.sizePolicy().hasHeightForWidth())
        self.lb_info.setSizePolicy(sizePolicy)
        self.lb_info.setText("")
        self.lb_info.setObjectName("lb_info")
        self.gridLayout.addWidget(self.lb_info, 3, 0, 1, 1)
        self.horizontal_main = QtWidgets.QHBoxLayout()
        self.horizontal_main.setObjectName("horizontal_main")
        self.vertical_catalogue = QtWidgets.QVBoxLayout()
        self.vertical_catalogue.setObjectName("vertical_catalogue")
        self.lb_catalogue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_catalogue.sizePolicy().hasHeightForWidth())
        self.lb_catalogue.setSizePolicy(sizePolicy)
        self.lb_catalogue.setObjectName("lb_catalogue")
        self.vertical_catalogue.addWidget(self.lb_catalogue)
        self.tv_catalogue = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tv_catalogue.sizePolicy().hasHeightForWidth())
        self.tv_catalogue.setSizePolicy(sizePolicy)
        self.tv_catalogue.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tv_catalogue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tv_catalogue.setObjectName("tv_catalogue")
        self.vertical_catalogue.addWidget(self.tv_catalogue)
        self.horizontal_main.addLayout(self.vertical_catalogue)
        self.vertical_file = QtWidgets.QVBoxLayout()
        self.vertical_file.setObjectName("vertical_file")
        self.lb_file = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_file.sizePolicy().hasHeightForWidth())
        self.lb_file.setSizePolicy(sizePolicy)
        self.lb_file.setObjectName("lb_file")
        self.vertical_file.addWidget(self.lb_file)
        self.lv_file = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_file.sizePolicy().hasHeightForWidth())
        self.lv_file.setSizePolicy(sizePolicy)
        self.lv_file.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lv_file.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_file.setObjectName("lv_file")
        self.vertical_file.addWidget(self.lv_file)
        self.horizontal_main.addLayout(self.vertical_file)
        self.vertical_label = QtWidgets.QVBoxLayout()
        self.vertical_label.setObjectName("vertical_label")
        self.lb_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_label.sizePolicy().hasHeightForWidth())
        self.lb_label.setSizePolicy(sizePolicy)
        self.lb_label.setObjectName("lb_label")
        self.vertical_label.addWidget(self.lb_label)
        self.lv_label = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_label.sizePolicy().hasHeightForWidth())
        self.lv_label.setSizePolicy(sizePolicy)
        self.lv_label.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lv_label.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_label.setObjectName("lv_label")
        self.vertical_label.addWidget(self.lv_label)
        self.horizontal_main.addLayout(self.vertical_label)
        self.horizontal_main.setStretch(0, 6)
        self.horizontal_main.setStretch(1, 4)
        self.horizontal_main.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontal_main, 2, 0, 1, 1)
        FileM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FileM)
        self.statusbar.setObjectName("statusbar")
        FileM.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(FileM)
        self.toolBar.setObjectName("toolBar")
        FileM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(FileM)
        QtCore.QMetaObject.connectSlotsByName(FileM)

    def retranslateUi(self, FileM):
        _translate = QtCore.QCoreApplication.translate
        FileM.setWindowTitle(_translate("FileM", "FileM"))
        self.label.setText(_translate("FileM", "地址栏"))
        self.lb_catalogue.setText(_translate("FileM", "目录栏"))
        self.lb_file.setText(_translate("FileM", "文件列表栏"))
        self.lb_label.setText(_translate("FileM", "标签列表栏"))
        self.toolBar.setWindowTitle(_translate("FileM", "toolBar"))

